CREATE DATABASE QLDULICH
ON
(
	NAME = 'QLDULICH_MDF',
	FILENAME = 'D:\Projects\Subjects\Travel Webstie\QLDULICH.MDF'
)
LOG ON
(
	NAME = 'QLDULICH_LOG',
	FILENAME = 'D:\Projects\Subjects\Travel Webstie\QLDULICH.LDF'
)
USE QLDULICH

CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) PRIMARY KEY,
	TENKH NVARCHAR(30) NOT NULL,
	NGAYSINH DATE NOT NULL,
	SDT_KHACHHANG VARCHAR(11) NOT NULL, CHECK(LEN(SDT_KHACHHANG) >= 8 AND LEN(SDT_KHACHHANG) < 11),
	DIACHI_KHACHHANG NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(20),
)
CREATE TABLE TINH_TP
(
	MA_T_TP CHAR(5) PRIMARY KEY,
	TEN_T_TP NVARCHAR(30) NOT NULL
)
CREATE TABLE CONGTY
(
	MACT CHAR(5) PRIMARY KEY,
	TENCT NVARCHAR(30) NOT NULL,
	SDT_CONGTY VARCHAR(11) NOT NULL, CHECK(LEN(SDT_CONGTY) >= 8 AND LEN(SDT_CONGTY) < 11),
	DIACHI NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(20)
)
CREATE TABLE DICHVU
(
	MADV CHAR(5) PRIMARY KEY,
	TENDV NVARCHAR(30) NOT NULL,
	GIA_DV MONEY NOT NULL
)
CREATE TABLE TOUR
(
	MATOUR CHAR(5) PRIMARY KEY,
	TENTOUR NVARCHAR(50) NOT NULL,
	DIACHI_TOUR NVARCHAR(50) NOT NULL,
	SLNGUOI INT NOT NULL,
	GIA_TOUR MONEY NOT NULL,
	MA_T_TP CHAR(5),
	MACT CHAR(5),
	MADV CHAR(5),
	FOREIGN KEY (MA_T_TP) REFERENCES TINH_TP (MA_T_TP),
	FOREIGN KEY (MACT) REFERENCES CONGTY (MACT),
	FOREIGN KEY (MADV) REFERENCES DICHVU (MADV)
)
CREATE TABLE HOADON
(
	MAHD CHAR(5) PRIMARY KEY,
	MAKH CHAR(5),
	NGAYLAP DATE NOT NULL,
	TONGTG MONEY,
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)
)
CREATE TABLE CTHD
(
	MAHD CHAR(5),
	MATOUR CHAR(5),
	PRIMARY KEY(MAHD, MATOUR),
	DIEMDI NVARCHAR(50) NOT NULL,
	DIDEN NVARCHAR(50) NOT NULL,
	NGAYDI DATE NOT NULL,
	NGAYVE DATE NOT NULL,
	SLKHACH INT NOT NULL,
	GIA MONEY NOT NULL,
	KHUYENMAI FLOAT
	FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD),
	FOREIGN KEY (MATOUR) REFERENCES TOUR (MATOUR)
)
